name: "NPM Release"
description: "Bump version based on commit history and publish to npm (main/dev workflow)."

inputs:
  npm-token:
    description: "npm token with publish rights"
    required: true
  build-script:
    description: "npm script to run before publishing"
    required: false
    default: "build"
  main-branch:
    description: "Main release branch"
    required: false
    default: "main"
  dev-branch:
    description: "Dev prerelease branch"
    required: false
    default: "dev"
  access:
    description: "npm publish access level (public or private)"
    required: false
    default: "public"

outputs:
  new-version:
    description: "New version published"
    value: ${{ steps.bump.outputs.new_version }}
  npm-latest:
    description: "Latest version previously on npm"
    value: ${{ steps.npm_tag.outputs.npm_v }}

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      fetch-depth: 0

  - uses: actions/setup-node@v4
    with:
      node-version: lts/*

  - name: Configure npm token
    shell: bash
    env:
      NPM_TOKEN: ${{ inputs.npm-token }}
    run: |
      npm config set //registry.npmjs.org/:_authToken="$NPM_TOKEN"

  - name: Read package.json
    id: pkg
    shell: bash
    run: |
      name=$(jq -r .name package.json)
      echo "name=$name" >> "$GITHUB_OUTPUT"

  - name: Get latest npm version
    id: npm_tag
    shell: bash
    env:
      DEV_BRANCH: ${{ inputs.dev-branch }}
      PKG_NAME: ${{ steps.pkg.outputs.name }}
    run: |
      branch=${GITHUB_REF##*/}

      if [[ "$branch" == "$DEV_BRANCH" ]]; then
        suffix="@dev"
      else
        suffix=""
      fi

      latest=$(npm view "${PKG_NAME}$suffix" version 2>/dev/null || echo "0.0.0")
      echo "npm_v=$latest" >> "$GITHUB_OUTPUT"

  - name: Determine new version
    id: bump
    shell: bash
    env:
      MAIN_BRANCH: ${{ inputs.main-branch }}
      DEV_BRANCH: ${{ inputs.dev-branch }}
      NPM_V: ${{ steps.npm_tag.outputs.npm_v }}
    run: |
      branch=${GITHUB_REF##*/}
      npm_v="$NPM_V"

      if [[ -z "$npm_v" || "$npm_v" == "null" ]]; then
        npm_v="0.0.0"
      fi

      if [[ "$branch" == "$MAIN_BRANCH" ]]; then
        if git log HEAD~10..HEAD --pretty=%B | grep -qE '!:|BREAKING CHANGE'; then
          level=major
        elif git log HEAD~10..HEAD --pretty=%s | grep -q '^feat'; then
          level=minor
        else
          level=patch
        fi
        new_ver=$(npx semver -i "$level" "$npm_v")

      elif [[ "$branch" == "$DEV_BRANCH" ]]; then
        base=$(echo "$npm_v" | sed 's/-dev\.[0-9]*//')
        if echo "$npm_v" | grep -q -- "-dev."; then
          prev=$(echo "$npm_v" | sed 's/.*-dev\.//')
          prev=${prev:-0}
          next=$((prev + 1))
        else
          next=0
        fi
        new_ver="${base}-dev.${next}"

      else
        echo "new_version=" >> "$GITHUB_OUTPUT"
        exit 0
      fi

      echo "new_version=$new_ver" >> "$GITHUB_OUTPUT"

  - name: Build and publish
    shell: bash
    if: ${{ steps.bump.outputs.new_version != '' }}
    env:
      BUILD_SCRIPT: ${{ inputs.build-script }}
      DEV_BRANCH: ${{ inputs.dev-branch }}
      NEW_VERSION: ${{ steps.bump.outputs.new_version }}
      ACCESS: ${{ inputs.access }}
    run: |
      npm install
      npm run "$BUILD_SCRIPT"
      npm version "$NEW_VERSION" --no-git-tag-version

      branch=${GITHUB_REF##*/}

      if [[ "$branch" == "$DEV_BRANCH" ]]; then
        npm publish --tag dev --access "$ACCESS"
      else
        npm publish --access "$ACCESS"
      fi
