name: Calculate new version
description: Calculate the new version to publish based on commits

inputs:
  npm-version:
    description: "Current npm version"
    required: true
  bump-level:
    description: "Version bump level (major, minor, patch)"
    required: false
    default: "patch"
  main-branch:
    description: "Main release branch"
    required: false
    default: "main"
  dev-branch:
    description: "Dev prerelease branch"
    required: false
    default: "dev"

outputs:
  version:
    description: "New version to publish"
    value: ${{ steps.bump.outputs.new_version }}

runs:
  using: composite
  steps:
  - name: Calculate new version
    id: bump
    shell: bash
    env:
      MAIN_BRANCH: ${{ inputs.main-branch }}
      DEV_BRANCH: ${{ inputs.dev-branch }}
      NPM_V: ${{ inputs.npm-version }}
      BUMP_LEVEL: ${{ inputs.bump-level }}
    run: |
      branch=${GITHUB_REF##*/}
      npm_v="$NPM_V"
      level="$BUMP_LEVEL"

      # Validate bump-level
      if [[ "$level" != "major" && "$level" != "minor" && "$level" != "patch" ]]; then
        echo "::error::Invalid bump-level '$level'. Must be one of: major, minor, patch"
        exit 1
      fi

      if [[ -z "$npm_v" || "$npm_v" == "null" ]]; then
        npm_v="0.0.0"
      fi

      if [[ "$branch" == "$MAIN_BRANCH" ]]; then
        new_ver=$(bunx semver -i "$level" "$npm_v")

      elif [[ "$branch" == "$DEV_BRANCH" ]]; then
        base=$(echo "$npm_v" | sed 's/-dev\.[0-9]*//')
        if echo "$npm_v" | grep -q -- "-dev."; then
          prev=$(echo "$npm_v" | sed 's/.*-dev\.//')
          prev=${prev:-0}
          next=$((prev + 1))
        else
          next=0
        fi
        new_ver="${base}-dev.${next}"

      else
        echo "new_version=" >> "$GITHUB_OUTPUT"
        exit 0
      fi

      echo "new_version=$new_ver" >> "$GITHUB_OUTPUT"
